### ISSUE TITLE
POT file syntax wrong for extracted ngettext function calls

### ISSUE THREAD

**Issue by maufl** [laget-se/react-gettext-parser#6]
In my code I have a `ngettext` function cal like 
```i18n.ngettext("Buy envelope", "Buy envelopes", 5)```
The corresponding part of the generated POT file looks like this:
```
#: web/static/js/components/react_test.js:14
msgid "Buy envelope"
msgid_plural "Buy envelopes"
msgstr ""
```
The tool I use to handle the POT files chokes on this, as it expects
```
#: web/static/js/components/react_test.js:14
msgid "Buy envelope"
msgid_plural "Buy envelopes"
msgstr[0] ""
```
I'm not sure if it is actually a bug or just unclear what a POT file entry for plural translations should look like.
Looking at the code I guess the relevant line is around https://github.com/laget-se/react-gettext-parser/blob/master/src/parse.js#L212, but I do not completely understand the code yet.

**Comment by maufl** [comment]
Actually, I think this might be a bug in `gettext-parser` which compiles the POT file.
https://github.com/andris9/gettext-parser/blob/master/lib/pocompiler.js#L104
It only writes `msgstr[0]` if the `msgstr` array has more than one element, instead of relying on the presence of a `msgid_plural` key.

**Comment by maufl** [comment]
I opened a pull request https://github.com/andris9/gettext-parser/pull/19 that should fix this issue.

**Comment by alexanderwallin** [comment]
@maufl Thanks for reporting! Whether or not a fix goes into this repo, we should setup up some tests to verify plural block definitions work properly.

**Comment by maufl** [comment]
The fix is merged, and after I updated my NPM dependencies, the problem disappeared :)
If I have time, I will write tests for this project too. However, it is already tested in `gettext-parser`.

**Comment by alexanderwallin** [comment]
@maufl Good stuff!

It's not entirely resolved for me. `gettext-parser` still loops through the `msgstr` array to create the

```gettext
msgstr[0] ""
msgstr[1] ""
```

output.

For components, we make sure to [add two empty strings](https://github.com/laget-se/react-gettext-parser/blob/master/src/parse.js#L48) into `msgstr`, whilst when parsing function calls [we don't](https://github.com/laget-se/react-gettext-parser/blob/master/src/parse.js#L212).

I'm working on a fix now!

**Comment by maufl** [comment]
Yes, I noticed that. It was just not a problem for my tool.
